import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

const Navbar = () => {
  return (
    <nav className="bg-indigo-600 shadow-md">
      <div className="max-w-7xl mx-auto px-4 py-4">
        <div className="flex justify-between items-center">
          <Link href="/">
            <h1 className="text-white text-3xl font-bold">Hotel Automation</h1>
          </Link>
          <div className="space-x-6">
            <Link href="/" className="text-white hover:text-indigo-300">
              Home
            </Link>

            <Link
              href="/reservation"
              className="text-white hover:text-indigo-300"
            >
              Reservations
            </Link>
            <Link href="/catering" className="text-white hover:text-indigo-300">
              Catering
            </Link>
            <Link href="/billing" className="text-white hover:text-indigo-300">
              Billing
            </Link>
            <Link href="/rooms" className="text-white hover:text-indigo-300">
              Admin
            </Link>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        {/* Footer */}
        <footer className="bg-indigo-800 text-white text-center py-6">
          <p>© 2025 Hotel Automation | All Rights Reserved</p>
        </footer>
      </body>
    </html>
  );
}
