import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 p-4">
        <ul className="flex justify-center space-x-8">
          <li><Link href="/guest" className="text-white hover:underline">Guest</Link></li>
          <li><Link href="/receptionist" className="text-white hover:underline">Receptionist</Link></li>
          <li><Link href="/admin" className="text-white hover:underline">Admin</Link></li>
          <li><Link href="/caterer" className="text-white hover:underline">Caterer</Link></li>
        </ul>
      </nav>
        {children}
        <footer className="bg-gray-800 text-white text-center py-4 mt-8">
      <p className="text-sm">
        Created by:
        <span className="font-semibold">Made by:  Sourav, Amlan and Pratik</span>
      </p>
      <p className="text-xs mt-2">All rights reserved &copy; 2025</p>
    </footer>
      </body>
    </html>
  );
}
